### ISSUE TITLE
Dependency conflict with analyzer ^1.5.0

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [Jesway/Flutter-Translate-Gen#11] opened 2021-11-16 21:49 UTC
flutter_translate_gen >=2.0.0 depends on analyzer ^1.5.0 and auto_route_generator 3.1.0 depends on analyzer ^2.7.0

upgrade analyzer to ^2.7.0

**Comment by cody1024d** [comment] 2021-12-10 20:20
I'm also facing this issue. It results in me having to use old versions of dependencies :(

**Comment by xzhorikx** [comment] 2021-12-11 10:27
Please upgrade the library asap to the latest analyzer dependency. Due to this conflict we had to revert to the libraries that are more than 6 months old

**Comment by bratan** [comment] 2021-12-11 13:08
Feel free to submit a PR.

These seems to be an issue with analyzer >= 2.0.0 which breaks the code generation.

**Comment by cody1024d** [comment] 2021-12-11 16:35
@bratan when you updated was it a silent error, or was that throwing something? 

The reason I asked is I moved over to the branch from PR #9, and have not noticed anything wrong?

**Comment by bratan** [comment] 2021-12-11 19:44
@cody1024d the specific error is below and occurs with any version of ```analyzer``` >= 2.0 when trying to run the build on the example project.

![image](https://user-images.githubusercontent.com/5787988/145689431-60db4e5d-7518-4b21-9119-b0e6484d759d.png)

I`m not sure what changes were introduced in analyzer 2.0 but I have no free time currently to investigate.

**Comment by xzhorikx** [comment] 2021-12-12 08:10
@cody1024d will you have the time to check the possible cause?

**Comment by cody1024d** [comment] 2021-12-12 16:25
@xzhorikx Potentially. I use it for a side project, so once it becomes a blocker for progress, I will have to take a look haha. I'll definitely submit a PR when I look into it.

I'm definitely fairly new to dart as a language, but based on the error, it should be fairly easy to track down.... I hope lol

**Comment by ema987** [comment] 2021-12-13 09:40
Hello, as @cody1024d said, I see no issues in the example project using the branch on PR #9 that I made. All the keys are correctly generated without errors.
Furthermore, I use it in a project much bigger than the example one without any issues.

@bratan could your error be caused by a different flutter version?

Here is my flutter doctor

```
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-x64, locale
    en-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
[✓] VS Code (version 1.63.0)
[✓] Connected device (1 available)
```

@cody1024d @xzhorikx in the meanwhile, if you want to use the updated library (or test it in your own projects) you can use

```
dependencies:
  flutter_translate: 3.0.1

dev_dependencies:
  flutter_translate_gen:
    git:
      url: https://github.com/ema987/flutter_translate_gen
      ref: feature/dependenciesUpdate
```

but it would be better if these changes will be merged in this repository and a new version published on pub.dev.

Thank you

**Comment by bratan** [comment] 2021-12-13 11:42
Hi @ema987, I've just tested the PR again, the issue occurs with Flutter version 2.5.3 as well as the newest 2.8.0, below is the complete output.

![image](https://user-images.githubusercontent.com/5787988/145805977-2436a8f4-cd55-4546-a0ca-78c585eb75bd.png)

**Comment by xzhorikx** [comment] 2021-12-13 11:45
https://stackoverflow.com/a/68987223
Could this be the possible cause of the issue?

Pasting the SO response

> I was facing the same problem right now. Finally figured out what I was doing wrong.
>
> The solution is the name of the dart file should be used in part"file_name.g.dart"; and there should be no gaps in the file name. For example, my dart file name was Data Entry.dart and I was using part"entries.g.dart";. That's why it was showing this error. Then I changed the code to part"Data Entry.g.dart";. It was still showing the error.
>
> Then finally I changed the file name to entries.dart and used part"entries.g.dart"; and it worked fine.

**Comment by bratan** [comment] 2021-12-13 11:49
@xzhorikx there are no gaps basically in any of the filenames or paths.

This is the detailed error when running --verbose:

![image](https://user-images.githubusercontent.com/5787988/145689431-60db4e5d-7518-4b21-9119-b0e6484d759d.png)

**Comment by bratan** [comment] 2021-12-13 11:54
Running on a Mac the build completes successfully, but not on Windows, so there is definitely a path related issue.

**Comment by ema987** [comment] 2021-12-13 13:49
@bratan thank you for your time. I confirm it works correctly on a Mac (11.6 BigSur) using both Flutter 2.5.3 and Flutter 2.8.0.

Unfortunately, I can not test on Windows at the moment.

**Comment by bratan** [comment] 2022-05-03 18:58
Fixed in https://github.com/Jesway/Flutter-Translate-Gen/commit/31786f464b31ebbe5da421b2594d5fc9371d164b

**Closed by bratan** 2022-05-03 18:58 UTC
